name: 'pr env'
description: 'Extract env from PR'
author: 'zzswang'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  text:
    description: 'Text to extract env'
    required: true

# Define your outputs here.
outputs:
  env:
    description: 'all env key values'

runs:
  using: node20
  main: dist/index.js
